from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class RejectionReason:
    code: str
    message: str
    category: str
    subcategory: str
    severity: str
    is_fatal: bool
    creator_action: str
    platform_action: str
    remediation: str
    localization_key: str
    docs_url: str


DOCS_BASE_URL = "https://originprotocol.dev/docs/errors/"


def _make_reason(
    code: str,
    message: str,
    category: str,
    subcategory: str,
    severity: str,
    creator_action: str,
    platform_action: str,
    remediation: str | None = None,
) -> RejectionReason:
    fatal_override = code in {"key_untrusted", "attestation_invalid", "revoked"}
    return RejectionReason(
        code=code,
        message=message,
        category=category,
        subcategory=subcategory,
        severity=severity,
        is_fatal=(severity == "critical" or category in {"crypto", "governance"} or fatal_override),
        creator_action=creator_action,
        platform_action=platform_action,
        remediation=remediation or creator_action,
        localization_key=f"origin.reason.{code}",
        docs_url=f"{DOCS_BASE_URL}{code}",
    )


REJECTION_REASONS: dict[str, RejectionReason] = {
    "sidecar_read_error": _make_reason(
        "sidecar_read_error",
        "Sidecar file could not be read",
        "transport",
        "sidecar",
        "medium",
        "Check sidecar path and file permissions.",
        "reject_upload",
    ),
    "bundle_manifest_missing": _make_reason(
        "bundle_manifest_missing",
        "bundle.json missing from payload",
        "transport",
        "bundle",
        "high",
        "Recreate the bundle; ensure bundle.json is included.",
        "reject_upload",
    ),
    "bundle_signature_missing": _make_reason(
        "bundle_signature_missing",
        "bundle.sig missing from payload",
        "transport",
        "bundle",
        "high",
        "Recreate the bundle; ensure bundle.sig is included.",
        "reject_upload",
    ),
    "media_read_error": _make_reason(
        "media_read_error",
        "Media file could not be read",
        "transport",
        "media",
        "medium",
        "Verify media path and file permissions.",
        "reject_upload",
    ),
    "manifest_invalid": _make_reason(
        "manifest_invalid",
        "Manifest JSON invalid",
        "integrity",
        "manifest",
        "high",
        "Regenerate the manifest from the original media.",
        "reject_upload",
    ),
    "public_key_invalid": _make_reason(
        "public_key_invalid",
        "Public key PEM invalid or not Ed25519",
        "crypto",
        "key",
        "critical",
        "Use a valid Ed25519 public key in PEM format.",
        "reject_upload",
    ),
    "payload_invalid_json": _make_reason(
        "payload_invalid_json",
        "Embedded Origin payload is not valid JSON",
        "transport",
        "container",
        "high",
        "Re-embed a valid Origin payload into the container.",
        "reject_upload",
    ),
    "payload_missing_keys": _make_reason(
        "payload_missing_keys",
        "Embedded Origin payload missing required keys",
        "transport",
        "container",
        "high",
        "Ensure all required Origin payload keys are present.",
        "reject_upload",
    ),
    "bundle_manifest_missing_entry": _make_reason(
        "bundle_manifest_missing_entry",
        "Bundle manifest missing required entry",
        "integrity",
        "bundle",
        "high",
        "Recreate the bundle to include all required entries.",
        "reject_upload",
    ),
    "bundle_manifest_hash_mismatch": _make_reason(
        "bundle_manifest_hash_mismatch",
        "Bundle manifest hash mismatch for embedded payload",
        "integrity",
        "bundle",
        "high",
        "Recreate the bundle and re-embed the payload.",
        "reject_upload",
    ),
    "signature_invalid": _make_reason(
        "signature_invalid",
        "Manifest signature invalid",
        "crypto",
        "signature",
        "critical",
        "Re-sign the manifest with the correct private key.",
        "reject_upload",
    ),
    "seal_invalid": _make_reason(
        "seal_invalid",
        "Seal signature invalid",
        "crypto",
        "signature",
        "critical",
        "Regenerate the seal and ensure the correct private key is used.",
        "reject_upload",
    ),
    "bundle_manifest_invalid": _make_reason(
        "bundle_manifest_invalid",
        "Bundle manifest signature invalid",
        "crypto",
        "signature",
        "critical",
        "Recreate the bundle to regenerate bundle.json and bundle.sig.",
        "reject_upload",
    ),
    "bundle_contents_mismatch": _make_reason(
        "bundle_contents_mismatch",
        "Bundle contents do not match bundle.json",
        "integrity",
        "canonicalization",
        "high",
        "Recreate the bundle from the original media and manifest.",
        "reject_upload",
    ),
    "bundle_hash_mismatch": _make_reason(
        "bundle_hash_mismatch",
        "Bundle file hash mismatch",
        "integrity",
        "hash",
        "high",
        "Ensure bundle files were not altered after signing.",
        "reject_upload",
    ),
    "asset_record_missing": _make_reason(
        "asset_record_missing",
        "Asset record missing from platform ledger",
        "policy",
        "ledger",
        "high",
        "Register the asset in the platform ledger before verification.",
        "require_manual_review",
    ),
    "content_hash_mismatch": _make_reason(
        "content_hash_mismatch",
        "Content hash mismatch",
        "integrity",
        "hash",
        "critical",
        "Upload the exact media used to generate the bundle.",
        "reject_upload",
    ),
    "platform_mismatch": _make_reason(
        "platform_mismatch",
        "Upload platform not in intended_platforms",
        "policy",
        "platform",
        "medium",
        "Add the platform to intended_platforms or re-sign for this platform.",
        "reject_upload",
    ),
    "platform_missing": _make_reason(
        "platform_missing",
        "Platform not specified",
        "policy",
        "platform",
        "low",
        "Specify the platform id when verifying.",
        "warn_creator",
    ),
    "creator_mismatch": _make_reason(
        "creator_mismatch",
        "Creator id mismatch",
        "identity",
        "creator",
        "high",
        "Verify creator_id matches the platform account.",
        "reject_upload",
    ),
    "key_id_missing": _make_reason(
        "key_id_missing",
        "Key id missing",
        "identity",
        "key_id",
        "medium",
        "Include key_id in the manifest for registry enforcement.",
        "warn_creator",
    ),
    "key_id_mismatch": _make_reason(
        "key_id_mismatch",
        "Key id mismatch",
        "identity",
        "key_id",
        "high",
        "Ensure manifest key_id matches the signing public key.",
        "reject_upload",
    ),
    "key_untrusted": _make_reason(
        "key_untrusted",
        "Key not trusted or inactive",
        "trust",
        "registry",
        "critical",
        "Register the key in the platform’s registry or generate a new active key.",
        "reject_upload",
    ),
    "revoked": _make_reason(
        "revoked",
        "Asset or key revoked",
        "governance",
        "revocation",
        "critical",
        "This asset or key has been revoked. Use a different key or re-issue the asset with a new manifest.",
        "reject_upload",
    ),
    "revocation_list_missing": _make_reason(
        "revocation_list_missing",
        "Revocation list missing",
        "governance",
        "revocation",
        "high",
        "Provide a revocation list for policy enforcement.",
        "require_manual_review",
    ),
    "revocation_signature_invalid": _make_reason(
        "revocation_signature_invalid",
        "Revocation list signature invalid",
        "governance",
        "revocation",
        "critical",
        "Regenerate the revocation list signature using the correct issuer key.",
        "reject_upload",
    ),
    "revocation_entry_invalid": _make_reason(
        "revocation_entry_invalid",
        "Revocation entry invalid",
        "governance",
        "schema",
        "high",
        "Recreate the revocation entry with valid fields.",
        "require_manual_review",
    ),
    "revocation_scope_unsupported": _make_reason(
        "revocation_scope_unsupported",
        "Revocation scope unsupported",
        "policy",
        "revocation",
        "medium",
        "Use a supported revocation scope or update the platform policy.",
        "require_manual_review",
    ),
    "revocation_issuer_untrusted": _make_reason(
        "revocation_issuer_untrusted",
        "Revocation issuer untrusted",
        "trust",
        "revocation",
        "high",
        "Ensure the revocation issuer is trusted by the platform.",
        "defer_to_trust_store",
    ),
    "revocation_conflict": _make_reason(
        "revocation_conflict",
        "Revocation conflict detected",
        "governance",
        "revocation",
        "high",
        "Resolve conflicting revocations and regenerate the list.",
        "require_manual_review",
    ),
    "seal_timestamp_invalid": _make_reason(
        "seal_timestamp_invalid",
        "Seal timestamp predates manifest",
        "integrity",
        "timing",
        "high",
        "Regenerate the seal after creating the manifest.",
        "reject_upload",
    ),
    "key_registry_missing": _make_reason(
        "key_registry_missing",
        "Key registry missing",
        "trust",
        "registry",
        "medium",
        "Provide a key registry for policy enforcement.",
        "require_manual_review",
    ),
    "seal_required": _make_reason(
        "seal_required",
        "Seal required by policy",
        "policy",
        "seal",
        "high",
        "Use a sealed bundle for this policy.",
        "reject_upload",
    ),
    "content_hash_unchecked": _make_reason(
        "content_hash_unchecked",
        "Content hash not verified",
        "policy",
        "content",
        "low",
        "Provide the media file to verify content hash.",
        "log_only",
    ),
    "attestation_missing": _make_reason(
        "attestation_missing",
        "Attestation missing",
        "trust",
        "attestation",
        "high",
        "Provide an issuer attestation for the creator key.",
        "reject_upload",
    ),
    "attestation_signature_missing": _make_reason(
        "attestation_signature_missing",
        "Attestation signature missing",
        "trust",
        "attestation",
        "high",
        "Include attestation.ed25519 with the attestation.",
        "reject_upload",
    ),
    "trust_store_missing": _make_reason(
        "trust_store_missing",
        "Trust store missing",
        "trust",
        "attestation",
        "high",
        "Provide a trust store of issuer keys.",
        "require_manual_review",
    ),
    "trust_store_empty": _make_reason(
        "trust_store_empty",
        "Trust store empty",
        "trust",
        "attestation",
        "high",
        "Add issuer keys to the trust store.",
        "require_manual_review",
    ),
    "attestation_creator_mismatch": _make_reason(
        "attestation_creator_mismatch",
        "Attestation creator mismatch",
        "trust",
        "attestation",
        "high",
        "Ensure attestation subject matches creator_id.",
        "reject_upload",
    ),
    "attestation_key_id_mismatch": _make_reason(
        "attestation_key_id_mismatch",
        "Attestation key id mismatch",
        "trust",
        "attestation",
        "high",
        "Ensure attestation subject_key_id matches manifest key_id.",
        "reject_upload",
    ),
    "attestation_key_mismatch": _make_reason(
        "attestation_key_mismatch",
        "Attestation public key mismatch",
        "trust",
        "attestation",
        "high",
        "Ensure attestation public key matches bundle public key.",
        "reject_upload",
    ),
    "attestation_expired": _make_reason(
        "attestation_expired",
        "Attestation expired or invalid",
        "trust",
        "timing",
        "high",
        "Renew or reissue the attestation.",
        "require_manual_review",
    ),
    "attestation_invalid": _make_reason(
        "attestation_invalid",
        "Attestation signature invalid",
        "trust",
        "attestation",
        "critical",
        "Request a new attestation from your issuer or verify that your issuer’s trust store is up to date.",
        "reject_upload",
    ),
    "attestation_platform_mismatch": _make_reason(
        "attestation_platform_mismatch",
        "Attestation platform binding mismatch",
        "trust",
        "attestation",
        "high",
        "Ensure attestation platform_binding matches the target platform.",
        "reject_upload",
    ),
    "attestation_region_mismatch": _make_reason(
        "attestation_region_mismatch",
        "Attestation region mismatch",
        "trust",
        "constraints",
        "high",
        "Ensure attestation region matches the platform requirements.",
        "reject_upload",
    ),
    "attestation_usage_violation": _make_reason(
        "attestation_usage_violation",
        "Attestation usage constraints violated",
        "trust",
        "constraints",
        "high",
        "Update usage constraints or request an attestation that permits this usage.",
        "reject_upload",
    ),
    "attestation_not_yet_valid": _make_reason(
        "attestation_not_yet_valid",
        "Attestation not yet valid",
        "trust",
        "timing",
        "high",
        "Wait until the attestation not_before timestamp or request an updated attestation.",
        "require_manual_review",
    ),
    "attestation_purpose_mismatch": _make_reason(
        "attestation_purpose_mismatch",
        "Attestation purpose mismatch",
        "trust",
        "constraints",
        "high",
        "Request an attestation with the required purpose.",
        "reject_upload",
    ),
    "container_payload_missing": _make_reason(
        "container_payload_missing",
        "Container payload missing",
        "integrity",
        "container",
        "high",
        "Re-embed the Origin payload or provide a sidecar.",
        "require_manual_review",
    ),
    "container_payload_invalid": _make_reason(
        "container_payload_invalid",
        "Container payload invalid",
        "integrity",
        "schema",
        "high",
        "Regenerate the container payload using the latest SDK.",
        "reject_upload",
    ),
    "container_signature_invalid": _make_reason(
        "container_signature_invalid",
        "Container payload signature invalid",
        "crypto",
        "signature",
        "critical",
        "Regenerate the container payload signature.",
        "quarantine_upload",
    ),
    "container_format_unsupported": _make_reason(
        "container_format_unsupported",
        "Container format unsupported",
        "policy",
        "container",
        "medium",
        "Use a supported container format or provide a sidecar.",
        "require_manual_review",
    ),
    "container_payload_mismatch": _make_reason(
        "container_payload_mismatch",
        "Container payload mismatch",
        "integrity",
        "container",
        "high",
        "Recreate the bundle and re-embed the payload.",
        "reject_upload",
    ),
    "bundle_missing_file": _make_reason(
        "bundle_missing_file",
        "Bundle missing required file",
        "integrity",
        "bundle",
        "high",
        "Recreate the bundle to include all required files.",
        "reject_upload",
    ),
    "bundle_unreadable": _make_reason(
        "bundle_unreadable",
        "Bundle unreadable or corrupted",
        "integrity",
        "bundle",
        "high",
        "Recreate the bundle and ensure it is not corrupted.",
        "reject_upload",
    ),
    "bundle_media_missing": _make_reason(
        "bundle_media_missing",
        "Bundle media missing",
        "integrity",
        "bundle",
        "high",
        "Recreate the bundle with the media file included.",
        "reject_upload",
    ),
    "bundle_media_path_invalid": _make_reason(
        "bundle_media_path_invalid",
        "Bundle media path invalid",
        "integrity",
        "bundle",
        "high",
        "Recreate the bundle to ensure media is under media/<filename>.",
        "reject_upload",
    ),
    "policy_violation": _make_reason(
        "policy_violation",
        "Policy violation",
        "policy",
        "policy",
        "high",
        "Adjust the policy configuration or use a compatible bundle.",
        "reject_upload",
    ),
    "policy_unsupported": _make_reason(
        "policy_unsupported",
        "Policy feature unsupported",
        "policy",
        "policy",
        "medium",
        "Upgrade the SDK or disable unsupported policy features.",
        "require_manual_review",
    ),
    "policy_input_missing": _make_reason(
        "policy_input_missing",
        "Policy input missing",
        "policy",
        "policy",
        "high",
        "Provide the required policy inputs (registry, revocation, attestation).",
        "defer_to_trust_store",
    ),
}


def format_reasons(codes: tuple[str, ...]) -> tuple[RejectionReason, ...]:
    return tuple(
        REJECTION_REASONS.get(
            code,
            _make_reason(
                code,
                code,
                "unknown",
                "unknown",
                "medium",
                "Review the verification configuration.",
                "log_only",
            ),
        )
        for code in codes
    )
